// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttVzNA0mF4ycd5GbGbCKOpVftJ3tCbPM',
    appId: '1:561884152123:web:a7b620faa51309d7d6371e',
    messagingSenderId: '561884152123',
    projectId: 'project-med-8c1df',
    authDomain: 'project-med-8c1df.firebaseapp.com',
    storageBucket: 'project-med-8c1df.appspot.com',
    measurementId: 'G-N44PPQ0NNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABG1DtaYxfQuIAS6YxakOWFE7SGw7C-E',
    appId: '1:561884152123:android:324f1cb1cd23967ed6371e',
    messagingSenderId: '561884152123',
    projectId: 'project-med-8c1df',
    storageBucket: 'project-med-8c1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOapmqvsTrNqzOTtcEt7IFcZFYa-cbeU',
    appId: '1:561884152123:ios:83ae4fc0dc4dc274d6371e',
    messagingSenderId: '561884152123',
    projectId: 'project-med-8c1df',
    storageBucket: 'project-med-8c1df.appspot.com',
    androidClientId: '561884152123-b31e8tgi0dajcba8h5doqtovuib00jqk.apps.googleusercontent.com',
    iosClientId: '561884152123-th11j3v4fuef3lfupvlkpundnvkilar7.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMed',
  );
}
